config/routes.rb
ItsNachoProblem::Application.routes.draw do

  get '/logout' => 'sessions#destroy', :as => 'logout'

  resources :admins, only: [:index, :create]

  resources :recipes, only: [:create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    collection do
      post 'favorite_recipe'
    end
    resources :ingredients, only: [:index, :new, :create] do
      collection do
        get 'search'
      end
    end
    get '/nachoresult' => 'recipes#show', as: 'nachoresult'
  end
  root to: 'users#index'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	attr_accessible :name
	validates_presence_of :name
	validates_uniqueness_of :name

  has_many :user_ingredients
  has_many :users, through: :user_ingredients

  include PgSearch
  pg_search_scope :search_by_name, :against => :name, :using => [:tsearch, :dmetaphone, :trigram], :ranked_by => ":trigram"

  def self.search(search)
  	Ingredient.search_by_name(search)
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  serialize :components
  attr_accessible :components, :name, :recipe_url, :img_url

  validates_presence_of :name, :recipe_url, :components, :img_url
  validates_uniqueness_of :name, :recipe_url

  has_many :user_recipes
  has_many :users, through: :user_recipes

end

  def new_recipe_from_yummly(api_result)
    recipe_name = ''
    recipe_url = ''
    recipe_img_url = ''
    recipe_components = []

    recipe = api_result.map do |recipe|
      recipe_name = recipe["recipeName"]
      recipe_url = "http://www.yummly.com/recipe/#{recipe['id']}"
      recipe_img_url = recipe["smallImageUrls"][0]
      recipe_components = recipe['ingredients']
    end
    api_params = {name: recipe_name, recipe_url: recipe_url, img_url: recipe_img_url, components: recipe_components}
  end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation

  validates_presence_of :password, :email, :on => :create
  validates :email, :uniqueness => true

  has_many :user_ingredients
  has_many :ingredients, through: :user_ingredients

  has_many :user_recipes
  has_many :recipes, through: :user_recipes

  has_secure_password

  def sort_recipes_by_ingredients(recipe_data, number_of_recipes)
    top_recipes = find_recipe_by_pantry(recipe_data).sort_by { |recipe_name, missing_ingredients| missing_ingredients.length }
    Hash[top_recipes.slice(0, number_of_recipes)]
  end
  
  
  def sort_recipes_by_percentage(top_recipes_hash)
    by_percent = get_percentage_of_missing_ingredients(top_recipes_hash).zip(find_top_recipes_in_db(top_recipes_hash))
    by_percent.sort_by { |recipe| recipe[0]}.reverse!
  end

  private

  def find_recipe_by_pantry(recipe_data)
    pantry_hashed = assign_ingredient_to_keyword
    found_recipes = {}
    recipe_data.map do |recipe_obj|
      found_recipes[recipe_obj.name] = recipe_obj.components.reject {|recipe| pantry_hashed[recipe[0..4]] }
    end
    found_recipes
  end

  def assign_ingredient_to_keyword
    get_user_ingredient_names.inject({}) {|hash, element| hash[element[0..[4, element.size].min]] = element; hash}
  end

  def get_user_ingredient_names
    self.ingredients.map do |obj|
      obj.name
    end
  end

  def find_top_recipes_in_db(top_recipes_hash)
    recipe_objects = []
    top_recipes_hash.each_key {|recipe_name| recipe_objects << Recipe.find_by_name(recipe_name)}
    recipe_objects
  end

  def get_percentage_of_missing_ingredients(top_recipes_hash)
    find_top_recipes_in_db(top_recipes_hash).map do |recipe|
      (100 - ((top_recipes_hash["#{recipe.name}"].length / recipe.components.length.to_f) * 100)).round(2)
    end
  end

end

app/models/user_ingredient.rb
class UserIngredient < ActiveRecord::Base
  belongs_to :user
  belongs_to :ingredient  
	validates_uniqueness_of :ingredient_id, :scope => :user_id  
end

app/models/user_recipe.rb
class UserRecipe < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe  
  validates_uniqueness_of :recipe_id, :scope => :user_id  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def yummly_search_result(user_pantry, max_results)
    result = Yummly.search(user_pantry, max_results)
    result.matches
  end

  def create
    api_result = yummly_search_result(params["/admins"]["ingredient"], {maxResult: params["/admins"]["max_result"]}) #=> hard coded, change ingredient and number of recipes
    api_result.length.times do
      Recipe.create(new_recipe_from_yummly(api_result))
      new_recipe_from_yummly(api_result)[:components].each do |ingredient|
        Ingredient.create(name: ingredient)
      end
      api_result.pop
    end
    redirect_to admins_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Authentication
  helper_method :current_user, :fetch_name
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate!
  
  def search
    @search = params[:search]
    @ingredients = Ingredient.search(@search)
    render partial: 'search_results', locals: {ingredients: @ingredients}
  end

end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController



  def yummly_search_result
    result = Yummly.search('Bacon')
    result.matches
  end

  def fetch_name
    recipe_names = yummly_search_result.map do |recipe|
      recipe["recipeName"]
    end 
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def show
    @top_recipes = current_user.sort_recipes_by_ingredients(Recipe.all, 45) #=> hard coded, changes number of recipes
    @recipe_objects = current_user.sort_recipes_by_percentage(@top_recipes)
    @paginatable_array = Kaminari.paginate_array(@recipe_objects).page(params[:page]).per(9)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if is_admin?
        redirect_to admins_path
      else
        redirect_to user_ingredients_path(user)
      end
    else
      flash[:error] = "Invalid email or password"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if logged_in?
      redirect_to user_ingredients_path(current_user)
    end
  end

  def create
    if params[:password] == params[:password_confirmation]
      user = User.new params[:user]
      user.password = params[:password]
      if user.save
        login user
        redirect_to user_ingredients_path(user)
      else
        flash[:error] = user.errors.full_messages.join(' : ')
      end
    else
      redirect_to root_path
    end
  end

  def update
    if current_user.save
      params[:ingredient_ids].length.times do |index|
        current_user.ingredients << Ingredient.find(params[:ingredient_ids][index])
      end
    end
    render :partial => "ingredients/user_pantry"
  end

  def show
    @user_favorites = current_user.recipes.page(params[:page]).per(9)
  end

  def favorite_recipe
    current_user.recipes << Recipe.find(params[:recipe_id])
    redirect_to user_path(current_user)
  end

  def destroy
    current_user.ingredients.destroy(params[:id])
    render :partial => "ingredients/user_pantry"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<h1>Admin</h1>
<%= form_for admins_path do |f| %>
  <%= f.label :ingredient %>
  <%= f.text_field :ingredient %>
  <%= f.text_field :max_result %>
  <%= f.submit 'Only 500 per day' %>
<% end %>

app/views/ingredients/_nacho.html.erb
<%= form_for @user, :url => user_nachoresult_path(@user), :method => :get do |f|%>
  <%= f.submit 'Nacho Problem', :class => "button radius right"%>
<% end %>

app/views/ingredients/_notices.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/ingredients/_search.html.erb
<%= form_tag search_user_ingredients_path(@user), :method => 'get', id: 'search-form', remote: true do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, :class => "button radius button left" %>
<% end %>

app/views/ingredients/_search_results.html.erb
<h3>Search results:</h3>
<%= form_for current_user, :remote => true do |f|  %>
<div class="search-results"> 
  <% @ingredients.each do |item| %>
  <%= check_box_tag 'ingredient_ids[]', item.id %> <%= item.name %><br>
  <% end %>  
</div>
<%= f.submit :value=>"Add to pantry", :class => "button radius" %>
<% end %>

app/views/ingredients/_user_pantry.html.erb
<h3>Items in your pantry:</h3>
<div class="search-results">
  <ul>
    <% current_user.ingredients.each do |ingredient| %>
    	<li><%= ingredient.name %> <%= button_to "x", {controller: :users, action: :destroy, id: ingredient.id,}, method: :delete, :remote => true %></li>
    <% end %>
  </ul>
</div>

app/views/ingredients/index.html.erb
 <h3 class="user_pantry"><%= current_user.username.titleize %>'s Pantry:</h3>

<!-- Search bar -->
<div class="user_pantry_div">
  <div class="row">
    <div class="small-12 large-6 large-centered columns ">
      <h3 class="text-center pantry-title">Add items to your pantry:</h3>
        <div class="clearfix">
        <%= render partial: 'ingredients/search' %>
        <%= render partial: 'ingredients/nacho' %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'ingredients/notices' unless flash.nil? %>

<div class="row">
  <div class="small-12 small-centered large-6 large-uncentered columns pantry-container">
    <%= render partial: 'user_pantry' %>
  </div>
  <div class="small-12 small-centered large-6 large-uncentered columns search-result-container">
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <section class="top-bar-section">
    <% if current_user.blank? %>
      <%= link_to "Sign Up!", "#", :id => "sign-up-link", :class => "right button radius" %>
      <%= link_to "Log In!", "#", :id => "login-link", :class => "right button radius" %>
    <% else %>
      <%= link_to "Back To Pantry", user_ingredients_path(current_user), :class => "button tiny radius right" %>
      <%= link_to "Favorites", favorite_recipe_users_path,:class => "right button tiny radius"%>
      <%= link_to "Log out", logout_path, :class => "right button tiny radius" %>
    <% end %>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Nacho Problem" %></title>

    <%= stylesheet_link_tag    "application" %>
  	<%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Coming+Soon'%>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="background" id="bg" >
      <%= render partial: 'layouts/header' %>
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<ol class="small-block-grid-1 large-block-grid-3 results">
  <% @paginatable_array.each_with_index do |recipe| %>
    <li>
      <ul class="recipes">
        <li><%= image_tag recipe[1].img_url, :class => "foodpic"%></li>
        <h6><li><%= recipe[1].name %></li></h6>
        <progress max="100" value ="<%= recipe[0] %>"></progress>
        <li><%= recipe[0] %>% Nacho Problem</li>
        <%= link_to "See more", "#", {:class => "see_more"} %>
        <div class='toggle hidden'>
          <li class='ingredient-bold'>Recipe Needs:</li>
          <li><%= recipe[1].components.join(', ')%></li>
          <br/>
          <li class='ingredient-bold'>Missing Ingredients:</li>
          <li><%= @top_recipes["#{recipe[1].name}"].join(', ') %></li>
          <li class="text-center"><%= link_to "See Recipe", "#{recipe[1].recipe_url}" %></li>
          <%= form_for current_user, :url => favorite_recipe_users_path, :method => "post" do |f| %>
            <%= hidden_field_tag("recipe_id", recipe[1].id) %>
            <%= f.submit :value=> "Add to favorites", :class => "button expand tiny round"%>
          <% end %>
        <div>
      </ul>
    </li>
  <% end %>
</ol>
<%= paginate @paginatable_array %>

app/views/recipes/show.html.erb
<div id="results-container">
  <div class="row"> 
      <%= render partial: "recipe" %>
  </div>
</div>

app/views/users/_favorite.html.erb
<ul class="small-block-grid-1 large-block-grid-3">
	<% @user_favorites.each do |favorite| %>
		<li>
			<ul class="favorites">
				<li><%= image_tag favorite.img_url, :class => "foodpic" %></li>
				<h6><li><%= favorite.name %></li></h6>
				<%= link_to "See more", "#", {:class => "see_more"} %>
				<div class='toggle hidden'>
					<li class='ingredient-bold'>Recipe Needs:</li>
					<li><%= favorite.components.join(', ')%></li>
					<br/>
					<li class="text-center"><%= link_to "See Recipe", "#{favorite.recipe_url}" %></li>
				</div>
			</ul>
		</li>
	<% end %>
</ul>

app/views/users/_favorites.html.erb
<ul class="small-block-grid-1 large-block-grid-3">
  <% @user_favorites.each do |favorite| %>
  <li>
    <ul class="favorites">
      <li><%= image_tag favorite.img_url, :class => "foodpic" %></li>
      <h6><li><%= favorite.name %></li></h6>
      <%= link_to "See more", "#", {:class => "see_more"} %>
      <div class='toggle hidden'>
          <li class='ingredient-bold'>Recipe Needs:</li>
          <li><%= favorite.components.join(', ')%></li>
          <br/>
          <li class="text-center"><%= link_to "See Recipe", "#{favorite.recipe_url}" %></li>
      </div>
    </ul>
  </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<div class="login-signup-container">
  <%= render partial: 'ingredients/notices' unless flash.nil? %>
  <div class="row">
    <div id="sign-up" class="small-12 large-12 large-centered columns sign-up-form">
      <h3>Sign Up:</h3>
      <%= form_for :user, url: users_path do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %><br>
        <%= f.label :email %>
        <%= f.email_field :email %><br>
        <%= label_tag :password %>
        <%= password_field_tag :password %><br>
        <%= label_tag :password_confirmation %>
        <%= password_field_tag :password_confirmation %><br>
        <%= f.submit 'Sign Up', :class => "button radius" %>
      <% end %>
    </div>

    <div id="log-in" class="small-12 large-12 large-centered columns ">
      <h3>Log In:</h3>
      <%= form_tag '/sessions' %>
      <%= label_tag :email %>
      <%= email_field_tag :email %><br>
      <%= label_tag :password %>
      <%= password_field_tag :password %><br>
      <%= submit_tag "Log In", :class => "button radius" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.errors.full_messages.first if @user.errors.any? %>

<h3><%= current_user.username.titleize %>'s Favorite Recipes:</h3>
<hr>

<div class="favorites-page">
	<div class="row">
		<div class="small-12 large-6 large-centered columns clearfix">
			<%= link_to "Your Pantry", user_ingredients_path(current_user), :class => "button radius left" %>
			<%= link_to "All Recipes", user_nachoresult_path(current_user), :class => "button radius right" %>
		</div>
	</div>
	<div class="row">
		<div class="results" id="favorite_recipe_list">
	  	<%= render partial: 'favorite' %>		
		</div>
	</div>
	<%= paginate @user_favorites %>
</div>